# Generated by Django 5.2.3 on 2025-06-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strayreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strayreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
